#ifdef REGISTER_WEAPON

REGISTER_WEAPON(WEAPON_ID_HAMMER, CHammer)
REGISTER_WEAPON(WEAPON_ID_PISTOL, CPistol)
REGISTER_WEAPON(WEAPON_ID_SHOTGUN, CShotgun)
REGISTER_WEAPON(WEAPON_ID_GRENADE, CGrenade)
REGISTER_WEAPON(WEAPON_ID_LASER, CLaserGun)
REGISTER_WEAPON(WEAPON_ID_NINJA, CNinja)

REGISTER_WEAPON(WEAPON_ID_EXPLODINGLASER, CExplodingLaser)

REGISTER_WEAPON(WEAPON_ID_JUGHAMMER, CJugHammer) // Hunter

REGISTER_WEAPON(WEAPON_ID_ASYLUM_PAN, CAsylumPan)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_KNIFE, CAsylumKnife)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_BAT, CAsylumBat)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_REVOLVER, CAsylumRevolver)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_SMG, CAsylumSMG)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_SHOTGUN, CAsylumShotgun)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_RAILGUN, CAsylumRailgun)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_LAUNCHER, CAsylumLauncher)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_MEDKIT, CAsylumMedkit)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_DASH, CAsylumDash)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_SHOCKWAVE, CAsylumShockwave)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_CLUSTER, CAsylumCluster)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_SPOON, CAsylumSpoon)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_DARKHEART, CAsylumDarkheart)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_ENERGYSWORD, CAsylumEnergySword)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_DYINGPAN, CAsylumDyingPan)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_CROSSBOW, CAsylumCrossbow)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_FREEZERAY, CAsylumFreezeRay)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_BAZOOKA, CAsylumBazooka)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_AMERICA, CAsylumAmerica)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_MANTLE, CAsylumMantle)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_REROLL, CAsylumReroll)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_PARASOL, CAsylumParasol)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_CLEAVE, CAsylumCleave)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_LILYNETTE, CAsylumLilynette)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_CHICAGO, CAsylumChicago)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_M1911, CAsylumM1911)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_BOW, CAsylumBow)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_PIXELGUN, CAsylumPixelGun)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_VAMPIREKNIVES, CAsylumVampireKnives)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_TASER, CAsylumTaser)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_HYPERLASER, CAsylumHyperlaser)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_UPGRADE_M1911, CAsylumUpgradeM1911)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_UPGRADE_PIXELGUN, CAsylumUpgradePixelGun)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_M1911_UPG, CAsylumM1911Upgrade)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_PIXELGUN_UPG, CAsylumPixelGunUpgrade)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_9MM, CAsylum9mm)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_SUPPRESSED_PISTOL, CAsylumSuppressedPistol)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_SSG08, CAsylumSSG08)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_BLASTER, CAsylumBlaster)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_UPGRADE_9MM, CAsylumUpgrade9mm)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_UPGRADE_SUPPRESSED, CAsylumUpgradeSuppressed)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_UPGRADE_SSG08, CAsylumUpgradeSSG08)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_MICROSMG, CAsylumMicroSMG)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_SUPPRESSED_MAC10, CAsylumSuppressedMAC10)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_AWP, CAsylumAWP)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_BANHAMMER, CAsylumBanhammer)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_BIRCHTREE, CAsylumBirchTree)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_ZENITH, CAsylumZenith)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_TSARBOMB, CAsylumTsarBomb)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_BLACKHOLE, CAsylumBlackhole)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_JUDGE, CAsylumJudge)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_TRAIN, CAsylumTrain)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_JUMPSCARE, CAsylumJumpscare)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_MOYAI, CAsylumMoyai)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_MICROPHONE, CAsylumMicrophone)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_MASTERSPARK, CAsylumMasterSpark)
REGISTER_WEAPON(WEAPON_ID_ASYLUM_THEWORLD, CAsylumTheWorld)

#else

#ifndef GAME_SERVER_WEAPONS_H
#define GAME_SERVER_WEAPONS_H

#include "weapons/grenade.h"
#include "weapons/hammer.h"
#include "weapons/lasergun.h"
#include "weapons/ninja.h"
#include "weapons/pistol.h"
#include "weapons/shotgun.h"

#include "weapons/explodinglaser.h"

#include "weapons/jughammer.h" // Hunter
#include "weapons/asylum.h"

enum
{
	// DDrace
	WEAPON_ID_DDRACE = -2,
	WEAPON_ID_WORLD = -1,
	WEAPON_ID_NONE = 0,
#define REGISTER_WEAPON(TYPE, CLASS) \
	TYPE,
#include <game/server/weapons.h>
#undef REGISTER_WEAPON
};

#endif // GAME_SERVER_WEAPONS_H

#endif // REGISTER_WEAPON
