name: Build

on: [push]

jobs:
  build-cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022]
        include:
        - os: ubuntu-24.04
          build-file: DDNet-Server
          server-file: TeeAsylum-Server
          env:
            CFLAGS: -Wdeclaration-after-statement -Werror
            CXXFLAGS: -Werror
        - os: windows-2022
          build-file: DDNet-Server.exe
          server-file: TeeAsylum-Server.exe
          env:
            CFLAGS: /WX
            CXXFLAGS: /WX
            LDFLAGS: /WX

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true

    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y
        sudo apt-get install libsqlite3-dev cmake -y

    - name: Build in release mode
      env: ${{ matrix.env }}
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=./
        cmake --build ./ --config Release

    - name: Move release
      if: contains(matrix.os, 'windows')
      run: mv ./release/${{ matrix.build-file }} ./

    - name: Package
      shell: bash
      run: |
        dir=artifacts/TeeAsylum-Expansion
        mkdir -p $dir/data
        cp ${{ matrix.build-file }} $dir/${{ matrix.server-file }}
        cp -r data/maps data/maps7 data/map-music $dir/data/
        cp -r room_config $dir/
        rm -r $dir/room_config/mapfiles
        cp package/*.cfg license.txt $dir/
        cp -r client-skins $dir/
        cp README.md $dir/
        mkdir -p $dir/assets/asylum
        cp assets/asylum/README.md $dir/assets/asylum/
        if [ "$RUNNER_OS" = Windows ]; then
          cp package/Start-TeeAsylum.cmd sqlite3.dll $dir/
        fi

    - name: Test package
      shell: bash
      timeout-minutes: 2
      run: |
        cp -r artifacts/TeeAsylum-Expansion test-run
        cd test-run
        ./${{ matrix.server-file }} -f autoexec.cfg shutdown

    - name: Upload Windows package
      if: contains(matrix.os, 'windows')
      uses: actions/upload-artifact@v7
      with:
        name: TeeAsylum-Expansion-Windows
        path: artifacts

    - name: Archive Linux package
      if: contains(matrix.os, 'ubuntu')
      run: tar -czf TeeAsylum-Expansion-Linux.tar.gz -C artifacts TeeAsylum-Expansion

    - name: Upload Linux package
      if: contains(matrix.os, 'ubuntu')
      uses: actions/upload-artifact@v7
      with:
        path: TeeAsylum-Expansion-Linux.tar.gz
        archive: false
